version: '3.7'
services:

  api.linfe:
    container_name: api.linfe
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        APP_STAGE: ${APP_STAGE}
        APP_ENV: ${APP_ENV}
    depends_on:
      - mysql.linfe
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./:/app
    ports:
      - "8001:80"
    networks:
      - bubble

  mysql.linfe:
    container_name: mysql.linfe
    image: mysql:8
    command: --max_allowed_packet=512M
    volumes:
      - linfe.mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    ports:
      - "33060:3306"
    networks:
      - bubble

volumes:
  linfe.mysql:

networks:
  bubble:
