version: '3.7'
services:
  web:
    container_name: web
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
    networks:
      - linfe

  php:
    container_name: php
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    hostname: api.linfe
    networks:
      - linfe

  mysql:
    container_name: mysql
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    container_name: redis
    image: 'bitnami/redis:latest'
    environment:
      ALLOW_EMPTY_PASSWORD: 1
    networks:
      - linfe

volumes:
  mysqldata:

networks:
  linfe: